"""PDF export service for analysis reports."""

import io
import json
from datetime import datetime


def generate_text_report(record: dict) -> str:
    """Generate a plain text report from an analysis record.

    Args:
        record: The analysis record dictionary.

    Returns:
        Formatted text report string.
    """
    analysis = record.get("analysis", {})
    lines = []

    lines.append("=" * 60)
    lines.append("RESUMEPILOT — AI RESUME ANALYSIS REPORT")
    lines.append("=" * 60)
    lines.append("")
    lines.append(f"File: {record.get('filename', 'Unknown')}")
    lines.append(f"Date: {record.get('uploaded_at', datetime.now().isoformat())}")
    lines.append(f"ATS Score: {analysis.get('ats_score', 'N/A')}/100")
    lines.append(f"AI Confidence: {analysis.get('ai_confidence', 'N/A')}")
    lines.append(f"Experience Level: {analysis.get('experience_level', 'N/A')}")
    lines.append("")

    lines.append("-" * 40)
    lines.append("PROFESSIONAL SUMMARY")
    lines.append("-" * 40)
    lines.append(analysis.get("summary", "No summary available."))
    lines.append("")

    lines.append("-" * 40)
    lines.append("STRENGTHS")
    lines.append("-" * 40)
    for s in analysis.get("strengths", []):
        lines.append(f"  ✓ {s}")
    lines.append("")

    lines.append("-" * 40)
    lines.append("WEAKNESSES")
    lines.append("-" * 40)
    for w in analysis.get("weaknesses", []):
        lines.append(f"  ✗ {w}")
    lines.append("")

    lines.append("-" * 40)
    lines.append("MISSING SKILLS")
    lines.append("-" * 40)
    for skill in analysis.get("missing_skills", []):
        lines.append(f"  • {skill}")
    lines.append("")

    lines.append("-" * 40)
    lines.append("IMPROVEMENT SUGGESTIONS")
    lines.append("-" * 40)
    for i, s in enumerate(analysis.get("suggestions", []), 1):
        lines.append(f"  {i}. {s}")
    lines.append("")

    lines.append("-" * 40)
    lines.append("INTERVIEW QUESTIONS")
    lines.append("-" * 40)
    for i, q in enumerate(analysis.get("interview_questions", []), 1):
        if hasattr(q, "question") or isinstance(q, dict):
            question_text = q.question if hasattr(q, "question") else q.get("question", "")
            answer_text = q.answer if hasattr(q, "answer") else q.get("answer", "")
            lines.append(f"  {i}. Q: {question_text}")
            if answer_text:
                lines.append(f"     A: {answer_text}")
        else:
            lines.append(f"  {i}. {q}")
    lines.append("")

    lines.append("-" * 40)
    lines.append("RECRUITER FEEDBACK")
    lines.append("-" * 40)
    lines.append(analysis.get("recruiter_feedback", "No feedback available."))
    lines.append("")

    if analysis.get("job_match_score") is not None:
        lines.append("-" * 40)
        lines.append(f"JOB MATCH SCORE: {analysis['job_match_score']}/100")
        lines.append("-" * 40)
        lines.append("")

    lines.append("-" * 40)
    lines.append("SKILL SCORES")
    lines.append("-" * 40)
    for skill in analysis.get("skill_scores", []):
        bar = "█" * (skill.get("score", 0) // 5) + "░" * (20 - skill.get("score", 0) // 5)
        lines.append(f"  {skill.get('name', '?'):20s} [{bar}] {skill.get('score', 0)}%")
    lines.append("")

    lines.append("=" * 60)
    lines.append("Generated by ProfileX AI AI — resumepilot.ai")
    lines.append("=" * 60)

    return "\n".join(lines)


def generate_json_export(record: dict) -> str:
    """Generate a JSON export of the analysis.

    Args:
        record: The analysis record dictionary.

    Returns:
        Pretty-printed JSON string.
    """
    return json.dumps(record, indent=2, default=str)
